### ISSUE TITLE
Any specific reason for the highWaterMark be set by default to 16?

### ISSUE THREAD

**Issue by daviddias** [mafintosh/parallel-transform#1]
After this commit - https://github.com/mafintosh/parallel-transform/commit/0ebda10604ecc2efb85cae1e09ca260ce99bd533 - the value for highWaterMark is set by default to 16. I'm trying to understand if there is any specific reason for that default value? 

Ran into some issues because I was expecting for a "drain" event when the buffer became empty, which doesn't happen if the highWaterMark is higher than the number of objects that are going to be fed to this stream.

**Comment by mafintosh** [comment]
Its because hwm used to default to 16k objects in node 0.10 (!) which would make your app run out of memory pretty fast. 0.12 fixed this so we can get rid of that now

**Comment by piglovesyou** [comment]
@diasdavid Maybe because the default highWaterMark in object mode stream is 16.
https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options
